### ISSUE TITLE
Exporting tables during xcms analysis

### ISSUE THREAD

**Issue by bwf7** [mjhelf/Metaboseek#136]
**Describe the bug**
Hi Max,
The peak_table export process is somehow not able to go to completion in my recent jobs. I get a peaktable_grouped.csv file and a peaktable_grouped_rtcorr.csv file only as R workspace files - they're not being written to excel files. I do get peaktable_unprocessed files (both rtcorr and not), but I am hesitant to use because they are not zero-filled and not normalized. 

**To Reproduce**
I set up a few jobs in a row with the same issue. Possible that it's a problem with these runs in particular, as I had no issues for a job of similar size (same samples, different LC).

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/52250575/60192649-36e85e00-9804-11e9-9a93-8130241b1a2c.png)

**Console output**
Aligning 20190624_05.mzXML against 20190624_04.mzXML ... Error in (function (x)  : attempt to apply non-function

**Desktop (please complete the following information):**

**Additional context**
Hi Max!

**Comment by bwf7** [comment]
Hi Max, I tried setting a different file as the first sample to see if it was an RT benchmark issue. I have the same problem... greetings from Ithaca.

**Comment by mjhelf** [comment]
Hi @bwf7 , does this happen with other datasets as well or just this one? Can you post the contents of the entire status.csv file, or send it to me by email? You know how to reach me ;)

**Comment by bwf7** [comment]
Hi Max, new data (and job), same issue. Thanks much for your help. Here's the status of the new job:

  | Time | Status | Details | elapsed_time
-- | -- | -- | -- | --
1 | 20190704_134222 | Finished | all analyses done, total time | 0
2 | 20190704_134215 | Saving table peaktable_grouped_Rtcorr_unprocessed.csv | Writing file | 6.82
3 | 20190704_134106 | Saving table peaktable_grouped_Rtcorr.csv | Getting Mseek intensities | 69.19
4 | 20190704_134055 | Saving table peaktable_grouped_Rtcorr.csv | Extracting peaktable | 11.06
5 | 20190704_130235 | Regroup peaks | group.density | 2300
6 | 20190704_130235 | Exporting data | Retention time correction information | 0.02
7 | 20190704_130157 | Retention time correction | obiwarp | 37.89
8 | 20190704_130151 | Saving table peaktable_grouped_unprocessed.csv | Writing file | 6.53
9 | 20190704_130048 | Saving table peaktable_grouped.csv | Getting Mseek intensities | 62.75
10 | 20190704_130036 | Saving table peaktable_grouped.csv | Extracting peaktable | 11.91
11 | 20190704_122529 | Group peaks | group.density | 2107.17
12 | 20190704_122522 | Exporting data | peaktable_all.csv | 6.92
13 | 20190704_121116 | Finding peaks | XcmsSet peak detection | 845.53
14 | 20190704_121057 | Starting analysis | loading files | 19.1
15 | 20190704_121057 | Starting analysis with xcms_runner in METABOseek v0.9.3 and xcms version   3.2.0 | initializing parameters | 0.08
